### ISSUE TITLE
Issue with 504 on fetch('/api/generate)

### ISSUE THREAD

**Issue by 0xGetM** [aleemrehmtulla/leap-template#1]
Any idea why I might be having this problem? I followed your Readme instructions but no image is being generated as the api is returning a 504

thanks

**Comment by aleemrehmtulla** [comment]
> Any idea why I might be having this problem? I followed your Readme instructions but no image is being generated as the api is returning a 504
> 
> thanks

wsp paul! will need more details :))

is the 504 on production or local? do you have a `.env` file?

**Comment by 0xGetM** [comment]
> > Any idea why I might be having this problem? I followed your Readme instructions but no image is being generated as the api is returning a 504
> > 
> > thanks
> 
> wsp paul! will need more details :))
> 
> is the 504 on production or local? do you have a `.env` file?
> 

Hey aleem, sure, I'm having this problem on the deployed version (kita-generator.vercel.app) and I've added both the env file on my local as well as on the vercel deployment environment variables

Thanks for your help man :)

**Comment by aleemrehmtulla** [comment]
> , sure, I'm having this problem on the deployed version (kita-generator.vercel.app) and I've added both the env file on my local as well as on the vercel deployment

of course! if it works on your local, it's most likely a timeout issue.

(vercel maxes out at 10s per call for free tier)

couple fixes: vercel pro, implement websockets w/ smthg like redis or firebase, host on a VM like digital ocean droplets

**Comment by 0xGetM** [comment]
> > , sure, I'm having this problem on the deployed version (kita-generator.vercel.app) and I've added both the env file on my local as well as on the vercel deployment
> 
> of course! if it works on your local, it's most likely a timeout issue.
> 
> (vercel maxes out at 10s per call for free tier)
> 
> couple fixes: vercel pro, implement websockets w/ smthg like redis or firebase, host on a VM like digital ocean droplets

Thank you for your insights man! I'll definitely look to understand more about that and check those fixes 

I'm not very pro with programming yet ahah 😅

Have a good week
