### ISSUE TITLE
Error: Forbidden You don't have access to this model

### ISSUE THREAD

**Issue by Ehtz** [aleemrehmtulla/leap-template#2]
Hello,

I've gone through the steps, loaded the page and compiled a prompt.
I am getting this error message from the host: Error: Forbidden You don't have access to this model
I've entered a correct ID and API key with a trained model on leap.
The setup step n'3 is not very clear I've created an .env file w the credential.

Thank you in advance

**Comment by aleemrehmtulla** [comment]
hey! this would be a issue with leap -- probably best to ask in their discord:)
